### ISSUE TITLE
Windows build broken

### ISSUE THREAD

**Issue by Anthchirp** [cctbx/cctbx_project#201]
Change happened between:

(first known broken commit to last known good commit)
* ~~a64a1db3887fc9e5ac07f9d6c6cb5b2d9bc81d7b Customized output stream to capture the print_pixel output for nks-specialized function. Will break existing Python code, but workaround exists to provide a dummy StringIO() stream.~~
* ~~eb62197e04a764f1a0407eeb884a953f99f420c2 allow origin shift in get_f_phases_from_map~~
* 0935282e12d5d117e4358fea101fb5e9b8e565d1 don't use with VS2015 or newer compilers
* 3c4ca467b182ff5f2b6009517ac56acd290ec11d -Dsomething preprocessor defines must be /Dsomething for Visual Studio compiler. Allow libtbx/sconscript to recognise VS2015 and VS2017 compilers
* 78ad33a9bf70e078f0238722aa93eccf35120b8a Update dxtbx.load's path-like handling to PEP519.

Build log:
```
cl /Focbflib\src\md5c.obj /c C:\Jenkins\workspace\dials_windows_build\dials\modules\cbflib\src\md5c.c /nologo /D_SECURE_SCL=0 /D_CRT_SECURE_NO_DEPRECATE /DNOMINMAX /DWIN32 /DDLL_EXPORTS /D_WIN32_WINNT=_WIN32_WINNT_WIN7 /bigobj /wd4996 /wd4068 /Z7 /Zm800 /MD /DNDEBUG /O2 /fp:fast /DBOOST_ALL_NO_LIB /DCBF_NO_REGEX /Dmalloc=malloc /Dfree=free /Ic:\jenkins\workspace\dials_windows_build\dials\base\include /Ic:\jenkins\workspace\dials_windows_build\dials\build\include /Ic:\jenkins\workspace\dials_windows_build\dials\modules\cctbx_project /Ic:\jenkins\workspace\dials_windows_build\dials\modules\cctbx_project /Ic:\jenkins\workspace\dials_windows_build\dials\modules\boost /Ic:\jenkins\workspace\dials_windows_build\dials\modules\cbflib /Ic:\jenkins\workspace\dials_windows_build\dials\modules\cbflib\examples /Ic:\jenkins\workspace\dials_windows_build\dials\modules\cbflib\include /Ic:\jenkins\workspace\dials_windows_build\dials\base\hdf5-1.8.16\include /Ic:\jenkins\workspace\dials_windows_build\dials\modules\cctbx_project\msvc9.0_include
md5c.c
cl /Focbflib_adaptbx\detectors\boost_python\cbflib_ext.obj /c C:\Jenkins\workspace\dials_windows_build\dials\modules\cctbx_project\cbflib_adaptbx\detectors\boost_python\cbflib_ext.cpp /GR /EHsc -DBOOST_PYTHON_MAX_BASES=2 /Ic:\jenkins\workspace\dials_windows_build\dials\modules\boost /nologo /D_SECURE_SCL=0 /D_CRT_SECURE_NO_DEPRECATE /DNOMINMAX /DWIN32 /DDLL_EXPORTS /D_WIN32_WINNT=_WIN32_WINNT_WIN7 /bigobj /wd4996 /wd4068 /Z7 /Zm800 /MD /DNDEBUG /O2 /fp:fast /DBOOST_ALL_NO_LIB /Ic:\jenkins\workspace\dials_windows_build\dials\base\include /Ic:\jenkins\workspace\dials_windows_build\dials\build\include /Ic:\jenkins\workspace\dials_windows_build\dials\modules\cctbx_project /Ic:\jenkins\workspace\dials_windows_build\dials\modules\cbflib /Ic:\jenkins\workspace\dials_windows_build\dials\modules\cbflib\examples /Ic:\jenkins\workspace\dials_windows_build\dials\modules\cbflib\include /Ic:\jenkins\workspace\dials_windows_build\dials\base\hdf5-1.8.16\include /Ic:\jenkins\workspace\dials_windows_build\dials\modules\cctbx_project\msvc9.0_include /IC:\Jenkins\workspace\dials_windows_build\dials\base\bin\python\Include
cbflib_ext.cpp
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/cstdint.hpp(106) : error C2039: 'int8_t' : is not a member of '`global namespace''
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/cstdint.hpp(106) : error C2873: 'int8_t' : symbol cannot be used in a using-declaration
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/cstdint.hpp(107) : error C2039: 'int_least8_t' : is not a member of '`global namespace''
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/cstdint.hpp(107) : error C2873: 'int_least8_t' : symbol cannot be used in a using-declaration
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/cstdint.hpp(108) : error C2039: 'int_fast8_t' : is not a member of '`global namespace''
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/cstdint.hpp(108) : error C2873: 'int_fast8_t' : symbol cannot be used in a using-declaration
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/cstdint.hpp(109) : error C2039: 'uint8_t' : is not a member of '`global namespace''
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/cstdint.hpp(109) : error C2873: 'uint8_t' : symbol cannot be used in a using-declaration
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/cstdint.hpp(110) : error C2039: 'uint_least8_t' : is not a member of '`global namespace''
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/cstdint.hpp(110) : error C2873: 'uint_least8_t' : symbol cannot be used in a using-declaration
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/cstdint.hpp(111) : error C2039: 'uint_fast8_t' : is not a member of '`global namespace''
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/cstdint.hpp(111) : error C2873: 'uint_fast8_t' : symbol cannot be used in a using-declaration
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/cstdint.hpp(113) : error C2039: 'int16_t' : is not a member of '`global namespace''
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/cstdint.hpp(113) : error C2873: 'int16_t' : symbol cannot be used in a using-declaration
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/cstdint.hpp(114) : error C2039: 'int_least16_t' : is not a member of '`global namespace''
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/cstdint.hpp(114) : error C2873: 'int_least16_t' : symbol cannot be used in a using-declaration
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/cstdint.hpp(115) : error C2039: 'int_fast16_t' : is not a member of '`global namespace''
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/cstdint.hpp(115) : error C2873: 'int_fast16_t' : symbol cannot be used in a using-declaration
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/cstdint.hpp(116) : error C2039: 'uint16_t' : is not a member of '`global namespace''
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/cstdint.hpp(116) : error C2873: 'uint16_t' : symbol cannot be used in a using-declaration
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/cstdint.hpp(117) : error C2039: 'uint_least16_t' : is not a member of '`global namespace''
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/cstdint.hpp(117) : error C2873: 'uint_least16_t' : symbol cannot be used in a using-declaration
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/cstdint.hpp(118) : error C2039: 'uint_fast16_t' : is not a member of '`global namespace''
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/cstdint.hpp(118) : error C2873: 'uint_fast16_t' : symbol cannot be used in a using-declaration
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/cstdint.hpp(120) : error C2039: 'int32_t' : is not a member of '`global namespace''
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/cstdint.hpp(120) : error C2873: 'int32_t' : symbol cannot be used in a using-declaration
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/cstdint.hpp(121) : error C2039: 'int_least32_t' : is not a member of '`global namespace''
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/cstdint.hpp(121) : error C2873: 'int_least32_t' : symbol cannot be used in a using-declaration
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/cstdint.hpp(122) : error C2039: 'int_fast32_t' : is not a member of '`global namespace''
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/cstdint.hpp(122) : error C2873: 'int_fast32_t' : symbol cannot be used in a using-declaration
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/cstdint.hpp(123) : error C2039: 'uint32_t' : is not a member of '`global namespace''
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/cstdint.hpp(123) : error C2873: 'uint32_t' : symbol cannot be used in a using-declaration
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/cstdint.hpp(124) : error C2039: 'uint_least32_t' : is not a member of '`global namespace''
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/cstdint.hpp(124) : error C2873: 'uint_least32_t' : symbol cannot be used in a using-declaration
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/cstdint.hpp(125) : error C2039: 'uint_fast32_t' : is not a member of '`global namespace''
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/cstdint.hpp(125) : error C2873: 'uint_fast32_t' : symbol cannot be used in a using-declaration
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/cstdint.hpp(129) : error C2039: 'int64_t' : is not a member of '`global namespace''
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/cstdint.hpp(129) : error C2873: 'int64_t' : symbol cannot be used in a using-declaration
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/cstdint.hpp(130) : error C2039: 'int_least64_t' : is not a member of '`global namespace''
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/cstdint.hpp(130) : error C2873: 'int_least64_t' : symbol cannot be used in a using-declaration
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/cstdint.hpp(131) : error C2039: 'int_fast64_t' : is not a member of '`global namespace''
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/cstdint.hpp(131) : error C2873: 'int_fast64_t' : symbol cannot be used in a using-declaration
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/cstdint.hpp(132) : error C2039: 'uint64_t' : is not a member of '`global namespace''
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/cstdint.hpp(132) : error C2873: 'uint64_t' : symbol cannot be used in a using-declaration
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/cstdint.hpp(133) : error C2039: 'uint_least64_t' : is not a member of '`global namespace''
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/cstdint.hpp(133) : error C2873: 'uint_least64_t' : symbol cannot be used in a using-declaration
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/cstdint.hpp(134) : error C2039: 'uint_fast64_t' : is not a member of '`global namespace''
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/cstdint.hpp(134) : error C2873: 'uint_fast64_t' : symbol cannot be used in a using-declaration
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/cstdint.hpp(138) : error C2039: 'intmax_t' : is not a member of '`global namespace''
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/cstdint.hpp(138) : error C2873: 'intmax_t' : symbol cannot be used in a using-declaration
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/cstdint.hpp(139) : error C2039: 'uintmax_t' : is not a member of '`global namespace''
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/cstdint.hpp(139) : error C2873: 'uintmax_t' : symbol cannot be used in a using-declaration
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/integer_fwd.hpp(29) : error C2039: 'uintmax_t' : is not a member of 'boost'
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/integer_fwd.hpp(29) : error C2146: syntax error : missing ';' before identifier 'static_min_max_unsigned_type'
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/integer_fwd.hpp(29) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/integer_fwd.hpp(30) : error C2039: 'intmax_t' : is not a member of 'boost'
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/integer_fwd.hpp(30) : error C2146: syntax error : missing ';' before identifier 'static_min_max_signed_type'
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/integer_fwd.hpp(30) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/integer_fwd.hpp(149) : error C2061: syntax error : identifier 'static_min_max_signed_type'
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/integer_fwd.hpp(150) : error C2992: 'boost::static_signed_min' : invalid or missing template parameter list
        c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/integer_fwd.hpp(150) : see declaration of 'boost::static_signed_min'
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/integer_fwd.hpp(152) : error C2061: syntax error : identifier 'static_min_max_signed_type'
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/integer_fwd.hpp(153) : error C2992: 'boost::static_signed_max' : invalid or missing template parameter list
        c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/integer_fwd.hpp(153) : see declaration of 'boost::static_signed_max'
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/integer_fwd.hpp(155) : error C2061: syntax error : identifier 'static_min_max_unsigned_type'
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/integer_fwd.hpp(156) : error C2992: 'boost::static_unsigned_min' : invalid or missing template parameter list
        c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/integer_fwd.hpp(156) : see declaration of 'boost::static_unsigned_min'
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/integer_fwd.hpp(158) : error C2061: syntax error : identifier 'static_min_max_unsigned_type'
c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/integer_fwd.hpp(159) : error C2992: 'boost::static_unsigned_max' : invalid or missing template parameter list
        c:\jenkins\workspace\dials_windows_build\dials\modules\boost\boost/integer_fwd.hpp(159) : see declaration of 'boost::static_unsigned_max'
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\atomic(1122) : error C2065: 'int8_t' : undeclared identifier
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\atomic(1122) : error C2923: 'std::atomic' : 'int8_t' is not a valid template type argument for parameter '_Ty'
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\atomic(1123) : error C2065: 'uint8_t' : undeclared identifier
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\atomic(1123) : error C2923: 'std::atomic' : 'uint8_t' is not a valid template type argument for parameter '_Ty'
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\atomic(1124) : error C2065: 'int16_t' : undeclared identifier
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\atomic(1124) : error C2923: 'std::atomic' : 'int16_t' is not a valid template type argument for parameter '_Ty'
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\atomic(1125) : error C2065: 'uint16_t' : undeclared identifier
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\atomic(1125) : error C2923: 'std::atomic' : 'uint16_t' is not a valid template type argument for parameter '_Ty'
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\atomic(1126) : error C2065: 'int32_t' : undeclared identifier
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\atomic(1126) : error C2923: 'std::atomic' : 'int32_t' is not a valid template type argument for parameter '_Ty'
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\atomic(1127) : error C2065: 'uint32_t' : undeclared identifier
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\atomic(1127) : error C2923: 'std::atomic' : 'uint32_t' is not a valid template type argument for parameter '_Ty'
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\atomic(1128) : error C2065: 'int64_t' : undeclared identifier
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\atomic(1128) : error C2923: 'std::atomic' : 'int64_t' is not a valid template type argument for parameter '_Ty'
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\atomic(1129) : error C2065: 'uint64_t' : undeclared identifier
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\atomic(1129) : error C2923: 'std::atomic' : 'uint64_t' is not a valid template type argument for parameter '_Ty'
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\atomic(1131) : error C2065: 'int_least8_t' : undeclared identifier
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\atomic(1131) : error C2923: 'std::atomic' : 'int_least8_t' is not a valid template type argument for parameter '_Ty'
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\atomic(1132) : error C2065: 'uint_least8_t' : undeclared identifier
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\atomic(1132) : error C2923: 'std::atomic' : 'uint_least8_t' is not a valid template type argument for parameter '_Ty'
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\atomic(1133) : error C2065: 'int_least16_t' : undeclared identifier
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\atomic(1133) : error C2923: 'std::atomic' : 'int_least16_t' is not a valid template type argument for parameter '_Ty'
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\atomic(1134) : error C2065: 'uint_least16_t' : undeclared identifier
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\atomic(1134) : error C2923: 'std::atomic' : 'uint_least16_t' is not a valid template type argument for parameter '_Ty'
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\atomic(1135) : error C2065: 'int_least32_t' : undeclared identifier
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\atomic(1135) : error C2923: 'std::atomic' : 'int_least32_t' is not a valid template type argument for parameter '_Ty'
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\atomic(1136) : error C2065: 'uint_least32_t' : undeclared identifier
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\atomic(1136) : error C2923: 'std::atomic' : 'uint_least32_t' is not a valid template type argument for parameter '_Ty'
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\atomic(1137) : error C2065: 'int_least64_t' : undeclared identifier
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\atomic(1137) : error C2923: 'std::atomic' : 'int_least64_t' is not a valid template type argument for parameter '_Ty'
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\atomic(1138) : error C2065: 'uint_least64_t' : undeclared identifier
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\atomic(1138) : error C2923: 'std::atomic' : 'uint_least64_t' is not a valid template type argument for parameter '_Ty'
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\atomic(1140) : error C2065: 'int_fast8_t' : undeclared identifier
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\atomic(1140) : error C2923: 'std::atomic' : 'int_fast8_t' is not a valid template type argument for parameter '_Ty'
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\atomic(1141) : error C2065: 'uint_fast8_t' : undeclared identifier
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\atomic(1141) : error C2923: 'std::atomic' : 'uint_fast8_t' is not a valid template type argument for parameter '_Ty'
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\atomic(1142) : error C2065: 'int_fast16_t' : undeclared identifier
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\atomic(1142) : fatal error C1003: error count exceeds 100; stopping compilation
scons: *** [cbflib_adaptbx\detectors\boost_python\cbflib_ext.obj] Error 2
scons: building terminated because of errors.
usr+sys time: 10.72 seconds
wall clock time: 3 minutes 53.86 seconds (233.86 seconds total)
```

**Comment by Oeffner** [comment]
I think this is a problem with https://github.com/cctbx/cctbx_project/commit/0935282e12d5d117e4358fea101fb5e9b8e565d1
I reckon it should be ```#if _MSC_VER <= 1800 ``` instead of ```#if _MSC_VER < 1400 ``` in both header files to allow for VS2012 to use the header files. But I haven't got this compiler so cannot test if it works. Could anyone at your end try it and then commit the code?

**Comment by Oeffner** [comment]
as per https://en.wikipedia.org/wiki/Microsoft_Visual_C%2B%2B#Internal_version_numbering

**Comment by Anthchirp** [comment]
Looking into this now.

**Comment by Anthchirp** [comment]
I can confirm this is caused by 0935282, but am out of time for today to fix this.

**Comment by Anthchirp** [comment]
@Oeffner as described in the commit message I've changed the version cutoffs like you suggested. I've also updated the header files, and as a result of this there is now one change in ```stdint.h``` for versions > 1800:
https://github.com/cctbx/cctbx_project/blob/f8972f64413130860dca2e299a94b9a385cdce70/msvc9.0_include/stdint.h#L44-L46

If this causes an issue on newer compilers then we could replace those three lines with
```cpp
#if _MSC_VER <= 1800 // [
```
again.
