### ISSUE TITLE
glib build issue

### ISSUE THREAD

**Issue by rimmartin** [cctbx/cctbx_project#13]
I'm hitting a new error.  This is with a fresh build folder and fresh wget https://raw.githubusercontent.com/cctbx/cctbx_project/master/libtbx/auto_build/bootstrap.py.  Building on a CentOS 6 box: 2.6.32-573.7.1.el6.centos.plus.x86_64 #1 SMP Wed Sep 23 03:02:55 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux and gcc 6.3.

Had built successfully with the same box and script Dec 22, 2016.  No changes to this box or compiler in the duration.

```
Installing glib...
  log file is /home/roger/Software/cctbx/base_tmp/glib_install_log
  getting package glib-2.46.2.tar.gz...
    downloading from http://cci.lbl.gov/cctbx_dependencies : 14.1 MB
    [0%.........20%.........40%.........60%.........80%.........100%]
  installing glib-2.46.2.tar.gz...
Traceback (most recent call last):
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 1450, in <module>
    installer(args=sys.argv, log=sys.stdout)
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 200, in __init__
    self.build_dependencies(packages=packages)
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 630, in build_dependencies
    getattr(self, 'build_%s'%i)()
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 1098, in build_glib
    log=pkg_log)
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 501, in configure_and_build
    self.call("make -j %d %s" % (nproc, " ".join(list(make_args))), log=log)
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 295, in call
    return call(args, log=log, verbose=self.verbose, **kwargs)
  File "/home/roger/Software/cctbx/modules/cctbx_project/libtbx/auto_build/installer_utils.py", line 81, in call
    raise RuntimeError("Call to '%s' failed with exit code %d" % (args, rc))
RuntimeError: Call to 'make -j 1 ' failed with exit code 2
Process failed with return code 1

**Comment by nwmoriarty** [comment]
Can you run 'make -j 1' or look in the glib_install_log for clues?

**Comment by rimmartin** [comment]
```
  CC       libglib_2_0_la-gdate.lo
gdate.c: In function 'g_date_strftime':
gdate.c:2497:7: error: format not a string literal, format string not checked [-Werror=format-nonliteral]
       tmplen = strftime (tmpbuf, tmpbufsize, locale_format, &tm);
       ^~~~~~
cc1: some warnings being treated as errors
make[4]: *** [libglib_2_0_la-gdate.lo] Error 1
make[4]: Leaving directory `/home/roger/Software/cctbx/base_tmp/glib-2.46.2/glib'
```

**Comment by Anthchirp** [comment]
I can help with the bootstrap script but I am not a C developer, and know little about glib.

**Comment by rimmartin** [comment]
I'm downloading glib directly  and testing building it.  I'll post if I find something

**Comment by bkpoon** [comment]
I just successfully built all the base dependencies with bootstrap.py on CentOS 6.7 with the standard gcc (4.4.7). Can you provide the config.log and Makefile files from your glib directory? I think it would be in "/home/roger/Software/cctbx/base_tmp/glib-2.46.2". It looks like you might have the "-Werror=format-nonliteral" flag set for gcc.

**Comment by rimmartin** [comment]
glib builds with gcc-5.3.0-01142016 on CentOS 6 but not gcc-6.3.0-01052017

yes, @bkpoon, it is the  "-Werror=format-nonliteral" involved. Might be default now with gcc 6.x; I do not see it explicitly set.

where did glib-2.46.2.tar.gz originate from?  I only find glib-html-2.46.2.tar.gz when looking for glib


[log_and_make.tar.gz](https://github.com/cctbx/cctbx_project/files/749100/log_and_make.tar.gz)

**Comment by rimmartin** [comment]
ah gnome is now on github
https://github.com/GNOME/glib

**Comment by bkpoon** [comment]
There is also https://ftp.gnome.org/pub/gnome/sources/glib/

We build and test with the compiler version that comes standard with the Linux distribution. The latest gcc compiler that is tested to work is gcc 5.4.0 on Ubuntu 16.04.4.

You can mess with the compiler flags that are passed to glib during the installation process by modifying cctbx/libtbx/auto_build/install_base_packages.py. There is a function called "build_glib" and line 1097 shows that the only configuration argument is the directory prefix for the installation. You can also define environment variables (e.g. CFLAGS, CXXFLAGS, etc). An example would be in the "build_pixman" function in the same file (starting at line 1172).

**Comment by rimmartin** [comment]
Thank you, @bkpoon, I'll look into this further; might fork and go further if I see a way forward

**Comment by bkpoon** [comment]
Let us know if you have any other issues. Thanks!
