### ISSUE TITLE
Multiplicity viewer does not work in Python 3

### ISSUE THREAD

**Issue by graeme-winter** [cctbx/cctbx_project#430]
Reported by user, verified by YT - 

```
Grey-Area DataFiles :) $ cctbx.multiplicity_viewer AUTOMATIC_DEFAULT_scaled_unmerged.mtz
/Users/graeme/svn/cctbx/build/../modules/cctbx_project/crys3d/command_line/multiplicity_viewer.py:41: wxPyDeprecationWarning: Call to deprecated item EmptyIcon. Use :class:`Icon` instead
  app_icon = wx.EmptyIcon()
AttributeError: module 'wx' has no attribute 'TaskBarIcon'
Traceback (most recent call last):
  File "/Users/graeme/svn/cctbx/build/../modules/cctbx_project/crys3d/command_line/multiplicity_viewer.py", line 496, in <module>
    run(sys.argv[1:])
  File "/Users/graeme/svn/cctbx/build/../modules/cctbx_project/crys3d/command_line/multiplicity_viewer.py", line 44, in run
    tb_icon = wx.TaskBarIcon(wx.TBI_DOCK)
AttributeError: module 'wx' has no attribute 'TaskBarIcon'
```

**Comment by rjgildea** [comment]
Does changing it to `wx.adv.TaskBarIcon` fix it (with added `import wx.adv`)?
https://wxpython.org/Phoenix/docs/html/wx.adv.TaskBarIcon.html#wx.adv.TaskBarIcon
https://wxpython.org/Phoenix/docs/html/classic_vs_phoenix.html

**Comment by graeme-winter** [comment]
```
Grey-Area command_line :) [master] $ git diff
diff --git a/crys3d/command_line/multiplicity_viewer.py b/crys3d/command_line/multiplicity_viewer.py
index 6b6f22687..bab0a023a 100644
--- a/crys3d/command_line/multiplicity_viewer.py
+++ b/crys3d/command_line/multiplicity_viewer.py
@@ -10,6 +10,7 @@ import iotbx.phil
 import libtbx.load_env
 from cctbx import crystal
 import wx
+import wx.adv
 import sys
 from six.moves import range
 from six.moves import zip
@@ -41,7 +42,7 @@ def run (args) :
   app_icon = wx.EmptyIcon()
   app_icon.CopyFromBitmap(icons.hklview_3d.GetBitmap())
   if (wx.VERSION >= (2,9)) :
-    tb_icon = wx.TaskBarIcon(wx.TBI_DOCK)
+    tb_icon = wx.adv.TaskBarIcon(wx.adv.TBI_DOCK)
   else :
     tb_icon = wx.TaskBarIcon()
   tb_icon.SetIcon(app_icon, "CCTBX multiplicity viewer")
```

pushes the problem along a bit:

```
Grey-Area DataFiles :( $ cctbx.multiplicity_viewer AUTOMATIC_DEFAULT_scaled_unmerged.mtz
/Users/graeme/svn/cctbx/build/../modules/cctbx_project/crys3d/command_line/multiplicity_viewer.py:42: wxPyDeprecationWarning: Call to deprecated item EmptyIcon. Use :class:`Icon` instead
  app_icon = wx.EmptyIcon()
/Users/graeme/svn/cctbx/modules/cctbx_project/crys3d/hklview/frames.py:426: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
  kind=wx.ITEM_NORMAL)
/Users/graeme/svn/cctbx/modules/cctbx_project/crys3d/hklview/frames.py:432: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
  kind=wx.ITEM_NORMAL)
/Users/graeme/svn/cctbx/modules/cctbx_project/crys3d/hklview/frames.py:438: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
  kind=wx.ITEM_NORMAL)
/Users/graeme/svn/cctbx/modules/cctbx_project/crys3d/hklview/frames.py:447: wxPyDeprecationWarning: Call to deprecated item. Use Append instead.
  self.file_menu.AppendItem(item)
/Users/graeme/svn/cctbx/modules/cctbx_project/crys3d/hklview/frames.py:481: wxPyDeprecationWarning: Call to deprecated item. Use Append instead.
  self.file_menu.AppendItem(item)
/Users/graeme/svn/cctbx/modules/cctbx_project/crys3d/hklview/frames.py:487: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
  kind=wx.ITEM_NORMAL)
/Users/graeme/svn/cctbx/modules/cctbx_project/crys3d/hklview/frames.py:493: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
  kind=wx.ITEM_NORMAL)
/Users/graeme/svn/cctbx/build/../modules/cctbx_project/crys3d/command_line/multiplicity_viewer.py:346: wxPyDeprecationWarning: Using deprecated class. Use Panel instead.
  wx.PyPanel.__init__(self, *args, **kwds)
NameError: name 'unicode' is not defined
Traceback (most recent call last):
  File "/Users/graeme/svn/cctbx/build/../modules/cctbx_project/crys3d/command_line/multiplicity_viewer.py", line 497, in <module>
    run(sys.argv[1:])
  File "/Users/graeme/svn/cctbx/build/../modules/cctbx_project/crys3d/command_line/multiplicity_viewer.py", line 58, in run
    f.load_reflections_file(settings.data)
  File "/Users/graeme/svn/cctbx/build/../modules/cctbx_project/crys3d/command_line/multiplicity_viewer.py", line 104, in load_reflections_file
    if (isinstance(file_name, unicode)) :
NameError: name 'unicode' is not defined
```

**Comment by graeme-winter** [comment]
Commenting out this check it works, so the diffs are sensible beyond this. No idea if will still work in Python 2.7 builds though.

**Comment by graeme-winter** [comment]
Change set at https://github.com/cctbx/cctbx_project/pull/new/fix-430

**Comment by rjgildea** [comment]
The call to wx.adv.TaskBarIcon (and possibly the import of wx.adv) should only be if wxpython4, otherwise it should stick to the previous code path if we want it to work with wxpython3.
I guess the unicode check could be moved under an `if six.PY2` statement?

**Comment by rjgildea** [comment]
I.e.
```
  if (wx.VERSION >= (4,0)) :
    import wx.adv
    tb_icon = wx.adv.TaskBarIcon(wx.adv.TBI_DOCK)
  elif (wx.VERSION >= (2,9)) :
    tb_icon = wx.TaskBarIcon(wx.TBI_DOCK)
  else :
    tb_icon = wx.TaskBarIcon()
```
and
```
    if six.PY2 and (isinstance(file_name, unicode)) :
      file_name = str(file_name)
```

**Comment by ndevenish** [comment]
I was under the impression that we used wxPython 4 on mac even for 2.7, so presumably it's been a problem on there for a while?

**Comment by graeme-winter** [comment]
@ndevenish same comment here applies directly to https://github.com/cctbx/cctbx_project/pull/431 so I am not sure how we missed these things

**Comment by dagewa** [comment]
Also
```
AttributeError: module 'wx' has no attribute 'SAVE'
```
after clicking the "Save image" button.

**Comment by dagewa** [comment]
For wxPython 4, this requires this line
https://github.com/cctbx/cctbx_project/blob/96897ddb8dc3c41b8a992fc8e58fa95ad3c36a9f/crys3d/hklview/frames.py#L734
to use `wx.FD_SAVE` instead. Similarly, this
https://github.com/cctbx/cctbx_project/blob/96897ddb8dc3c41b8a992fc8e58fa95ad3c36a9f/crys3d/hklview/frames.py#L726
should use `wx.FD_OPEN`

**Comment by Anthchirp** [comment]
Suspect this has been resolved by https://github.com/cctbx/cctbx_project/pull/474
Please reopen if this is not the case
