### ISSUE TITLE
[2023.11] does not compile with boost 1.83

### ISSUE THREAD

**Issue by picca** [cctbx/cctbx_project#944]
Hello, while updating the Debian cctbx package , I found this issue

Have a nice day.

Fred

```
In file included from /builds/science-team/cctbx/debian/output/source_dir/boost_adaptbx/tests/python_streambuf_test_ext.cpp:5:
/usr/include/boost/timer.hpp:21:3: error: #error This header is deprecated and will be removed. (You can define BOOST_TIMER_ENABLE_DEPRECATED to suppress this error.)
   21 | # error This header is deprecated and will be removed. (You can define BOOST_TIMER_ENABLE_DEPRECATED to suppress this error.)
      |   ^~~~~
In file included from /usr/include/boost/function/detail/requires_cxx11.hpp:9,
                 from /usr/include/boost/function/detail/prologue.hpp:12,
                 from /usr/include/boost/function/function_template.hpp:13,
                 from /usr/include/boost/function/detail/maybe_include.hpp:15,
                 from /usr/include/boost/function/function0.hpp:11,
                 from /usr/include/boost/python/errors.hpp:13,
                 from /usr/include/boost/python/handle.hpp:11,
                 from /usr/include/boost/python/to_python_value.hpp:14,
                 from /usr/include/boost/python/default_call_policies.hpp:10,
                 from /usr/include/boost/python/make_function.hpp:10,
                 from /usr/include/boost/python/def.hpp:11,
                 from /builds/science-team/cctbx/debian/output/source_dir/boost_adaptbx/tests/python_streambuf_test_ext.cpp:2:
/usr/include/boost/timer.hpp:25:1: note: ‘#pragma message: This header is deprecated. Use the facilities in <boost/timer/timer.hpp> instead.’
   25 | BOOST_HEADER_DEPRECATED( "the facilities in <boost/timer/timer.hpp>" )
      | ^~~~~~~~~~~~~~~~~~~~~~~
scons: *** [boost_adaptbx/tests/python_streambuf_test_ext.o] Error 1
scons: building terminated because of errors.
```

**Comment by bkpoon** [comment]
Yes, I have some changes in testing to fix this deprecation. I can commit it in a day or two.

**Comment by bkpoon** [comment]
Here is a branch with the changes. I'll do a test with Boost 1.83.

https://github.com/cctbx/cctbx_project/tree/boost_timer
